express-crud - Skylar Shaffer
skylarshaffer/c03-24-code-solutions pull request #129
Opened 2024-06-03 20:57 UTC by skylarshaffer

pre-modularization

2024-06-03 21:03 UTC, RobertGardner requested changes
Minor bugs.

2024-06-03 21:03 UTC, RobertGardner commented on express-crud/server.ts
> +    score === undefined && missing.push('score');
Also check that `score` is between 0 and 100.

2024-06-03 21:03 UTC, RobertGardner commented on express-crud/server.ts
> +      if (!Number.isInteger(+score)) {
You should do the isInteger check before the "between 0 and 100" check because if 'score' is a string instead of a number, then `score > 100` will be false, so this inner check will never execute.

2024-06-04 03:03 UTC, skylarshaffer commented on express-crud/server.ts
> +      if (!Number.isInteger(+score)) {
Thanks! Fixed.

2024-06-04 03:04 UTC, skylarshaffer commented on express-crud/server.ts
> +    score === undefined && missing.push('score');
Thanks! Fixed.

2024-06-04 03:04 UTC, merged